apiVersion: serving.knative.dev/v1
kind: Route
metadata:
  name: blue-green-demo # Route name is unchanged, since we're updating an existing Route
  namespace: demo
spec:
  traffic:
    - revisionName: blue-green-demo-rt225
      percent: 0 # All traffic still going to the first revision
    - revisionName: blue-green-demo-nk5nq
      percent: 100 # 0% of traffic routed to the second revision
      tag: v2 # A named route
